name: Build Chronos Mobile APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-22.04 # Specifica una versione LTS stabile

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies and Buildozer
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install "cython<3.0" buildozer
        python3 -m pip install kivy==2.2.1 pandas openpyxl Pillow

    - name: Configure buildozer.spec
      run: |
        buildozer init
        sed -i 's/title = My Application/title = Chronos Mobile/' buildozer.spec
        sed -i 's/package.name = myapp/package.name = chronos/' buildozer.spec
        sed -i 's/package.domain = org.test/package.domain = com.crk969/' buildozer.spec
        sed -i 's/# requirements = python3,kivy/requirements = python3,kivy==2.2.1,pandas,openpyxl,Pillow/' buildozer.spec
        sed -i 's/# android.permissions = INTERNET/android.permissions = WRITE_EXTERNAL_STORAGE,READ_EXTERNAL_STORAGE/' buildozer.spec
        sed -i 's/# icon.filename = %(appdir)s\/data\/icon.png/icon.filename = %(appdir)s\/icon.png/' buildozer.spec
        # Disabilita il download automatico dell'SDK/NDK da parte di buildozer
        sed -i 's/# android.skip_sdk_install = False/android.skip_sdk_install = True/' buildozer.spec

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Build with Buildozer
      run: buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: chronos-mobile-apk
        path: bin/*.apk
