name: Build Chronos Mobile APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libncurses5 libffi-dev libssl-dev \
            openjdk-11-jdk zip unzip

      - name: Install Buildozer and dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install "cython<3.0" buildozer

      - name: Rigenera buildozer.spec
        run: |
          cat <<EOF > buildozer.spec
[app]
title = Chronos Mobile
package.name = chronos
package.domain = com.crk969
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
version = 1.0
requirements = python3,kivy==2.2.1,pandas,openpyxl,Pillow
orientation = portrait
icon.filename = %(appdir)s/icon.png

[buildozer]
log_level = 2
warn_on_root = 1
allow_root = 1
android.api = 33
EOF

      - name: Cache Buildozer global directory
        uses: actions/cache@v4
        with:
          path: ~/.buildozer
          key: buildozer-global-v2

      - name: Build with Buildozer
        id: buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer -v android debug
          workdir: .

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chronos-mobile-apk
          path: bin/*.apk
