name: Build Chronos Mobile APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip build-essential git python3-dev libsdl2-2.0-0 libsdl2-image-2.0-0 libsdl2-mixer-2.0-0 libsdl2-ttf-2.0-0

    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install "cython<3.0" buildozer

    - name: Initialize Buildozer spec file
      run: buildozer init

    - name: Configure buildozer.spec
      run: |
        sed -i 's/title = My Application/title = Chronos Mobile/' buildozer.spec
        sed -i 's/package.name = myapp/package.name = chronos/' buildozer.spec
        sed -i 's/package.domain = org.test/package.domain = com.crk969/' buildozer.spec
        sed -i 's/# requirements = python3,kivy/requirements = python3,kivy==2.2.1,pandas,openpyxl,Pillow/' buildozer.spec
        sed -i 's/# android.permissions = INTERNET/android.permissions = WRITE_EXTERNAL_STORAGE,READ_EXTERNAL_STORAGE/' buildozer.spec
        sed -i 's/# icon.filename = %(appdir)s\/data\/icon.png/icon.filename = %(appdir)s\/icon.png/' buildozer.spec
        
    - name: Pre-accept Android SDK Licenses
      run: |
        yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses

    - name: Build the APK
      run: buildozer -v android debug

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: chronos-mobile-apk
        path: bin/*.apk
