name: Build Chronos Mobile APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip git zip unzip openjdk-11-jdk python3-venv ant
          
      - name: Install Buildozer and dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install "cython<3.0" buildozer
          python3 -m pip install kivy==2.2.1 pandas openpyxl Pillow

      - name: Build with Buildozer
        run: buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: chronos-mobile-apk
          path: bin/*.apk
